# Generated by Django 5.1 on 2024-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="astronomyshow",
            name="description",
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="description",
            field=models.TextField(default="add description"),
        ),
    ]
