# Generated by Django 5.1 on 2024-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_astronomyshow_show_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="show_theme",
            new_name="show_themes",
        ),
        migrations.AddField(
            model_name="showtheme",
            name="shows",
            field=models.ManyToManyField(
                related_name="themes", to="planetarium.astronomyshow"
            ),
        ),
    ]
