# Generated by Django 5.1 on 2024-08-28 13:41

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0006_remove_showtheme_shows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.astronomy_show_image_file_path
            ),
        ),
    ]
